M48
; DRILL file {KiCad (6.0.9)} date Sun 27 Nov 2022 02:52:21 AM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-27T02:52:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X69.25Y-44.76
X69.25Y-79.55
X131.74Y-44.76
X131.74Y-79.55
T0
M30
